In [64]:
import pandas as pd
from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
from sklearn.pipeline import Pipeline
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

In [65]:
df=pd.read_csv('spam.csv',encoding_errors='ignore')
df.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [66]:
df.drop(columns=['Unnamed: 2','Unnamed: 3','Unnamed: 4'],inplace=True)

In [67]:
df.head()

     v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [68]:
x=df['v2']
y=df['v1']

In [69]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,train_size=0.8,random_state=42)

In [70]:
pipeline=Pipeline(steps=[
    ('count',CountVectorizer()),
    ('model',MultinomialNB())
])
pipeline.fit(xtrain,ytrain)

Pipeline(steps=[('count', CountVectorizer()), ('model', MultinomialNB())])

In [71]:
pipeline1=Pipeline(steps=[
    ('count',TfidfVectorizer()),
    ('model',MultinomialNB())
])
pipeline1.fit(xtrain,ytrain)

Pipeline(steps=[('count', TfidfVectorizer()), ('model', MultinomialNB())])

In [78]:
pipeline2=Pipeline(steps=[
    ('count',TfidfVectorizer()),
    ('model',LogisticRegression())
])
pipeline2.fit(xtrain,ytrain)

Pipeline(steps=[('count', TfidfVectorizer()), ('model', LogisticRegression())])

In [72]:
ypred_xtrain=pipeline.predict(xtrain)
ypred_xtest=pipeline.predict(xtest)

In [73]:
ypred_xtrain1=pipeline1.predict(xtrain)
ypred_xtest1=pipeline1.predict(xtest)

In [79]:
ypred_xtrain2=pipeline2.predict(xtrain)
ypred_xtest2=pipeline2.predict(xtest)

# multinomial and countVector

In [81]:
print(classification_report(ytrain,ypred_xtrain))
print(classification_report(ytest,ypred_xtest))

              precision    recall  f1-score   support

         ham       1.00      1.00      1.00      3860
        spam       0.98      0.97      0.98       597

    accuracy                           0.99      4457
   macro avg       0.99      0.99      0.99      4457
weighted avg       0.99      0.99      0.99      4457

              precision    recall  f1-score   support

         ham       0.98      1.00      0.99       965
        spam       0.99      0.89      0.94       150

    accuracy                           0.98      1115
   macro avg       0.98      0.95      0.96      1115
weighted avg       0.98      0.98      0.98      1115

# multinomial and Tfidf

In [82]:
print(classification_report(ytrain,ypred_xtrain1))
print(classification_report(ytest,ypred_xtest1))

              precision    recall  f1-score   support

         ham       0.97      1.00      0.98      3860
        spam       1.00      0.80      0.89       597

    accuracy                           0.97      4457
   macro avg       0.98      0.90      0.94      4457
weighted avg       0.97      0.97      0.97      4457

              precision    recall  f1-score   support

         ham       0.96      1.00      0.98       965
        spam       1.00      0.72      0.84       150

    accuracy                           0.96      1115
   macro avg       0.98      0.86      0.91      1115
weighted avg       0.96      0.96      0.96      1115

In [80]:
print(classification_report(ytrain,ypred_xtrain2))
print(classification_report(ytest,ypred_xtest2))

              precision    recall  f1-score   support

         ham       0.97      1.00      0.99      3860
        spam       1.00      0.82      0.90       597

    accuracy                           0.98      4457
   macro avg       0.98      0.91      0.94      4457
weighted avg       0.98      0.98      0.97      4457

              precision    recall  f1-score   support

         ham       0.96      1.00      0.98       965
        spam       0.99      0.75      0.86       150

    accuracy                           0.97      1115
   macro avg       0.98      0.88      0.92      1115
weighted avg       0.97      0.97      0.96      1115